kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t wiki-mkdocs .

- name: deploy
  commands:
    - cd /var/docker/wiki
    - docker-compose stop docs-prod 
    - docker-compose up -d docs-prod